[package]
name = "fsrs-rs-dart"
version = "0.1.0"
edition = "2021"

[dependencies]
flutter_rust_bridge = "2.7.0"
fsrs = "2.0.2"

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
