name: Build and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  FLUTTER_VERSION: "3.19.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.22

      - name: Install flutter_rust_bridge_codegen
        run: |
          cargo binstall --no-confirm --no-symlinks cargo-expand
          cargo binstall --no-confirm --no-symlinks flutter_rust_bridge_codegen --version "^2.0.0"

      - name: Generate bridge code
        run: |
          mkdir -p fsrs_rs_dart/lib/bridge/frb_generated
          flutter_rust_bridge_codegen generate

      - name: rust ci
        run: |
          cd rust
          cargo fmt --all -- --check
          cargo clippy -- -D warnings
          cargo build --verbose
          cargo test --verbose

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze
